### ISSUE TITLE
Missing SVG support for classList

### ISSUE THREAD

**Issue by necolas** [remy/polyfills#40]
I believe you have to use `el.setAttribute('class', 'blah')` to be able to update the attribute on an SVG element, but it might be a bit tricker than that once you throw IE into the mix.

**Comment by jerone** [comment]
+1 This seems to work on IE (IE9+) for me.

**Comment by paulyn000** [comment]
also the hasAttribute must be supported

**Comment by tremby** [comment]
Was this fixed?
